Repository arborchat/muscadine, pull requests merged in 2019-01, with the labels that each got.

#83 Fix PR templates
  .github/PULL_REQUEST_TEMPLATE/pr-bugfix.md
  .github/pull_request_template.md
Labels: bug

#92 Bump muscadine to use newer protocol
  Gopkg.lock
  Gopkg.toml
Labels: bug

#87 Support all valid architectures for target OSes
  build-releases.sh
Labels: enhancement

#90 Open archive in read-write so we can save it
  archive/archive_manager_test.go
  archive/manager.go
Labels: bug

#89 Remove deprecated multicodec implementation from dependencies
  Gopkg.lock
  Gopkg.toml
  archive/archive.go
  archive/archive_test.go
Labels: debt

#85 Create build script to track version numbers
  README.md
  build-releases.sh
  build.sh
  main.go
  version.go
Labels: enhancement

#91 Darklaunch session tracking
  Gopkg.lock
  client.go
  composer.go
  session/list.go
  session/list_test.go
  tui/tui.go
  types/interfaces.go
Labels: enhancement

#96 Highlight descendant messages
  archive/archive.go
  archive/archive_test.go
  tui/history_state.go
  types/interfaces.go
Labels: enhancement
